import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import {
  IonContent, IonHeader, IonTitle, IonToolbar,
  IonItem, IonLabel, IonInput, IonSelect, IonSelectOption,
  IonButton, IonTextarea, IonButtons, IonIcon,
  IonList
} from '@ionic/angular/standalone';
import { ApiService } from '../api.service';
import { HelperService } from '../helper.service';
import { Category, Inventory, StockStatus } from '../app.component';

/**
 * Tab2 Page Component :Add Inventory Item Tab
 * Handles form input and submission for new inventory items
 */
@Component({
  selector: 'app-tab2',
  templateUrl: './tab2.page.html',
  styleUrls: ['./tab2.page.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    IonHeader, IonToolbar, IonTitle, IonContent,
    IonItem, IonLabel, IonInput, IonSelect, IonSelectOption,
    IonButton, IonTextarea, IonButtons, IonIcon,
    IonList
  ]
})
export class Tab2Page {
  // New inventory item form model (initialized with default values)
  newItem: Inventory = {
    item_id: 0, // Will be generated by API service
    item_name: '',
    category: Category.Electronics, // Default category
    quantity: 0,
    price: 0,
    supplier_name: '',
    stock_status: StockStatus.InStock, // Default stock status
    featured_item: 0, // Not featured by default
    special_note: ''
  };

  // Category options for select dropdown (extracted from enum)
  categories = Object.values(Category);
  // Stock status options for select dropdown (extracted from enum)
  stockStatuses = Object.values(StockStatus);

  /**
   * Constructor for Tab2Page
   * @param apiService - Inventory data service (CRUD operations)
   * @param helperService - UI helper service (toast, help dialogs)
   */
  constructor(
    private apiService: ApiService,
    private helperService: HelperService
  ) {}

  /**
   * Handle form submission
   * Validates form inputs and calls API to add new item
   */
  onSubmit() {
    // Form validation: check required fields and valid values
    if (!this.newItem.item_name || !this.newItem.supplier_name || this.newItem.quantity < 0 || this.newItem.price <= 0) {
      this.helperService.showToast('Please fill all required fields correctly', 'warning');
      return; // Exit if validation fails
    }

    // Call API to add new item
    this.apiService.addItem(this.newItem).subscribe({
      next: () => {
        this.helperService.showToast('Item added successfully!', 'success'); // Success feedback
        this.resetForm(); // Clear form after successful submission
      },
      error: (err) => {
        console.error(err); // Log error to console
        this.helperService.showToast('Add failed: ' + err.message, 'error'); // Error feedback
      }
    });
  }

  /**
   * Reset form to default values
   * Clears all input fields and resets to initial state
   */
  resetForm() {
    this.newItem = {
      item_id: 0,
      item_name: '',
      category: Category.Electronics,
      quantity: 0,
      price: 0,
      supplier_name: '',
      stock_status: StockStatus.InStock,
      featured_item: 0,
      special_note: ''
    };
  }

  /**
   * Show add item help dialog
   * Triggers helper service to display add-item-related help content
   */
  showHelp() {
    this.helperService.showHelp('add');
  }
}